version: '3.9'
services:
    db:
        image: postgres:latest
        container_name: my-postgres
        restart: always
        hostname: postgresql
        volumes:
            - ~/Documents/docker-vol/postgres-volume/data:/var/lib/postgresql/data
            - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
            - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
        environment:
             POSTGRES_DB: 'postgresdb'
             POSTGRES_USER: 'master'
             POSTGRES_PASSWORD: 'pas1234'
        ports:
            - '5432:5432'

    db-admin:
        depends_on:
            - db
        image: dpage/pgadmin4:latest
        restart: always
        container_name: pg-admin
        ports:
            - '8081:80'
        environment:
            PGADMIN_DEFAULT_PASSWORD: 'pas1234'
            PGADMIN_DEFAULT_EMAIL: 'debuggeandoideas@gmail.com'